import 'package:flutter/material.dart';

final Map<String, Map<String, String>> localizedValues = {
  'en': {
    'app_title': '4th Step Inventory',
    'form_title': 'Form',
    'entries_title': 'Entries',
    'settings_title': 'Settings',
    'data_management': 'Data Management',
    'export_json': 'Export to JSON',
    'import_json': 'Import from JSON',
    'clear_all': 'Clear All Entries',
    'cancel': 'Cancel',
    'confirm_clear': 'This will delete all entries permanently. Continue?',
    'delete_entry': 'Delete Entry',
    'delete_confirm': 'Are you sure you want to delete this entry?',
    'delete': 'Delete',
    'edit_entry': 'Edit Entry',
    'entry_deleted': 'Entry deleted successfully',
    'my_take': 'My take',
    'shortcomings': 'Shortcommings',
    'affect_my': 'Affects my',
    'i_am': 'I Am',
    'i_am_definitions': 'I Am Definitions',
    'add_i_am': 'Add I Am',
    'edit_i_am': 'Edit I Am',
    'delete_i_am': 'Delete I Am',
    'i_am_name': 'I Am name',
    'reason': 'The Cause',
    'reason_to_exist_optional': 'Reason to exist',
    'select_i_am': 'Select I Am',
    'no_i_am_selected': 'Standard (no I Am)',
    'confirm_delete_i_am': 'Delete this I Am definition?',
    'i_am_name_required': 'I Am name is required',
    'search': 'Search',
    'select_app': 'Select App',
    'switched_to_app': 'Switched to %s',
    'save_changes': 'Save Changes',
    'add_entry': 'Add Entry',
    'cancel_edit': 'Cancel Edit',
    // App names and descriptions
    'app_fourth_step_name': '4th Step Inventory',
    'app_fourth_step_desc': 'Resentment inventory',
    'app_eighth_step_name': '8th Step Amends',
    'app_eighth_step_desc': 'List of persons to make amends to',
    'app_evening_ritual_name': 'Evening Ritual',
    'app_evening_ritual_desc': 'Daily evening reflection and inventory',
    'app_morning_ritual_name': 'Morning Ritual',
    'app_morning_ritual_desc': 'Daily morning meditation and prayer routine',
    'app_gratitude_name': 'Gratitude',
    'app_gratitude_desc': 'Daily gratitude journal',
    'app_agnosticism_name': 'Surrender & Correction',
    'app_agnosticism_desc': 'What I haven\'t given to God & corrective attitudes',
    'googlefetch': 'Fetch data from Google Drive and overwrite local data',
    'sync_google_drive': 'Sync with Google Drive',
    'sign_in_google': 'Sign In with Google',
    'sign_out_google': 'Sign Out Google',
    'signed_in': 'Signed in to Google',
    'signed_out': 'Signed out',
    'enable_sync': 'Enable Sync?',
    'enable_sync_prompt': 'Would you like to enable automatic Google Drive sync to keep your data backed up?',
    'not_now': 'Not Now',
    'enable': 'Enable',
    'sync_complete': 'Sync complete',
    'sync_failed': 'Sync failed',
    'warning': 'Warning',
    'continue': 'Continue',
    'export_success': 'Export successful',
    'drive_upload_success': 'Drive upload successful (%s entries)',
    'no_entries': 'No entries',
    'confirm_google_fetch': 'Fetch data from Google Drive and overwrite local data?',
    'fetch': 'Fetch',
    'fetching_data': 'Fetching data from Google Drive...',
    'select_restore_point': 'Select Restore Point',
    'restore_point_latest': 'Latest (Current)',
    'restore_from_backup': 'Restore from Backup',
    'loading_backups': 'Loading backups...',
    'no_backups_available': 'No backups available',
    'part_tooltip': 'Have I been Selfish, dishonest, self-seeking or frightened?',
    'close': 'Close',
    'edit': 'Edit',
    'switch_app': 'Switch App',
    'refresh_backups': 'Refresh backups',
    'back_to_list': 'Back to list',
    'sign_in_to_enable_sync': 'Sign in with Google to enable sync',
    'cannot_delete_i_am_in_use': 'Cannot delete "%name%" because it is used by %count% entries.\n\nPlease remove or change the I Am for those entries first.',
    'resentment': 'I\'m resentful at',
    'switch_list_view': 'Switch to List View',
    'switch_table_view': 'Switch to Table View',
    // Error and status messages
    'failed_load_backups': 'Failed to load backups',
    'sign_in_no_token': 'Google sign-in succeeded but no access token was returned',
    'drive_init_failed': 'Drive initialization failed',
    'drive_not_available': 'Google Drive sync not available',
    'fetch_failed': 'Fetch failed',
    'json_saved': 'JSON saved to',
    'export_failed': 'Export failed',
    'import_failed': 'Import failed',
    'import_success': 'Imported %d entries, %d I Am definitions, %d people, %d reflections',
    'fetch_success': 'Successfully fetched from Google Drive',
    'sign_in_failed': 'Sign-in failed',
    'sign_in_cancelled': 'Sign-in failed or cancelled',
    'no_data_found': 'No data found in Google Drive',
    'fetch_success_count': 'Successfully fetched %entries% entries, %iams% I Am definitions from Google Drive',
    'no_entries_found': 'No entries found in Google Drive',
    'offline_backups': 'Offline Backups',
    'save_json_export': 'Save JSON Export',
    'export_data': 'Export Data',
    'help': 'Help',
    'information': 'Information',
    'help_not_available': 'Help content not available for this app.',
    'clear_warning': 'This will delete all data permanently. Continue?',
    'clear': 'Clear',
    'all_cleared': 'All data cleared',
    'import_success_count': 'Imported %entries% entries, %iams% I Am definitions, %people% people, %reflections% reflections',
    // Language names (keep as-is, these are proper nouns)
    'lang_english': 'English',
    'lang_danish': 'Dansk',
    // 8th Step Amends
    'eighth_step_title': '8th Step list',
    'eighth_step_main_tab': 'Main',
    'eighth_step_view_tab': 'View',
    'eighth_step_yes': 'Yes',
    'eighth_step_no': 'No',
    'eighth_step_maybe': 'Maybe',
    'add_person': 'Add Person',
    'edit_person': 'Edit Person',
    'delete_person': 'Delete Person',
    'person_name': 'Name',
    'amends': 'Amends',
    'amends_needed': 'Amends Needed',
    'amends_done': 'Amends Done',
    'amends_done_question': 'Amends Done?',
    'column': 'Column',
    'enter_name': 'Enter name',
    'enter_amends': 'Enter amends needed',
    'confirm_delete_person': 'Delete this person?',
    'person_name_required': 'Name is required',
    'optional': 'Optional',
    'select_person_prompt': 'Select a person from the Main tab',
    'import_from_drive': 'Import from Google Drive',
    'import': 'Import',
    'upload_to_drive_manual': 'Upload to Google Drive (Manual)',
    'google_authorization': 'Google Authorization',
    'copied_url': 'I\'ve Copied the URL',
    'import_warning': 'This will REPLACE all current data (entries and I Am definitions) with the imported data.\n\nMake sure you have exported your current data first!\n\nContinue with import?',
    // Evening Ritual
    'evening_ritual_title': 'Evening Ritual',
    'evening_ritual_form_tab': 'Today',
    'evening_ritual_list_tab': 'History',
    'reflection_type_resentful': 'I was resentful towards',
    'reflection_type_selfish': 'I was selfish when',
    'reflection_type_dishonest': 'I was dishonest when',
    'reflection_type_afraid': 'I was afraid when',
    'reflection_type_apology_owed': 'I owe an apology to',
    'reflection_type_kept_to_myself': 'I kept to myself (should have shared)',
    'reflection_type_kind_loving': 'I was kind and loving toward',
    'reflection_type_could_do_better': 'I could have done better by',
    'reflection_type_gods_forgiveness': 'God\'s forgiveness (what I ask for)',
    'reflection_type_corrective_measures': 'Corrective measures (what will I do tomorrow)',
    'add_reflection': 'Add Reflection',
    'edit_reflection': 'Edit Reflection',
    'reflection_detail': 'Detail',
    'thinking_focus_question': 'Where was my attention focused today?',
    'thinking_self': 'Thinking of myself',
    'thinking_others': 'Thinking of others',
    'slider_completely_self': 'Completely Self-Focused',
    'slider_mostly_self': 'Mostly Self-Focused',
    'slider_leaning_self': 'Leaning Self-Focused',
    'slider_balanced': 'Balanced',
    'slider_leaning_others': 'Leaning Others-Focused',
    'slider_mostly_others': 'Mostly Others-Focused',
    'slider_completely_others': 'Completely Others-Focused',
    'save_reflection': 'Save',
    'reflection_saved': 'Reflection saved',
    'no_reflections': 'No reflections yet',
    'no_reflections_hint': 'Tap the calendar to add your first evening reflection',
    'reflection_entries_count': '%d entries',
    'delete_reflection': 'Delete Reflection',
    'delete_reflection_confirm': 'Delete this reflection?',
    'reflection_deleted': 'Reflection deleted',
    'select_reflection_type': 'Select reflection type',
    'past_date_read_only': 'This date is in the past and cannot be edited. Only today\'s entry can be modified.',
    'delete_day': 'Delete All Reflections',
    'confirm_delete_day': 'Delete all {count} reflections for {date}?',
    'day_deleted': 'All reflections deleted',
    // Gratitude
    'gratitude_title': 'Gratitude',
    'gratitude_today_tab': 'Today',
    'gratitude_view_tab': 'View',
    'gratitude_today_subtitle': 'What are you grateful for today?',
    'gratitude_add_entry': 'Add Gratitude',
    'gratitude_edit_entry': 'Edit Gratitude',
    'gratitude_towards_label': 'Gratitude towards',
    'gratitude_towards_hint': 'Person, place, or thing',
    'gratitude_for_label': 'Grateful for',
    'gratitude_for_hint': 'What about them are you grateful for?',
    'gratitude_no_entries': 'No gratitude entries yet',
    'gratitude_no_entries_today': 'No gratitude entries for today',
    'gratitude_no_entries_hint': 'Start your gratitude journal in the Today tab',
    'gratitude_entries_count': '%d entries',
    'gratitude_delete_title': 'Delete Gratitude',
    'gratitude_delete_confirm': 'Delete this gratitude entry?',
    'update': 'Update',
    'add': 'Add',
    // Agnosticism
    'agnosticism_title': 'Agnosticism',
    'agnosticism_paper_tab': 'Paper',
    'agnosticism_archive_tab': 'Archive',
    'agnosticism_barriers_title': 'Not Given to God (Front)',
    'agnosticism_powers_title': 'God-Given Corrective Attitude (Back)',
    'agnosticism_flip': 'Flip Paper',
    'agnosticism_add_pair': 'Add Pair',
    'agnosticism_edit_pair': 'Edit Pair',
    'agnosticism_empty_paper': 'No pairs yet.\nTap "Add Pair" to start.',
    'agnosticism_empty_archive': 'No archived pairs yet',
    'agnosticism_barrier': 'Not Given to God',
    'agnosticism_power': 'Corrective Attitude',
    'agnosticism_barrier_hint': 'What have I not surrendered to God?',
    'agnosticism_power_hint': 'What God-given attitude corrects this?',
    'agnosticism_barrier_required': 'This field is required',
    'agnosticism_power_required': 'This field is required',
    'agnosticism_update': 'Update',
    'agnosticism_add': 'Add',
    'agnosticism_archive': 'Archive',
    'agnosticism_archive_title': 'Archive Pair',
    'agnosticism_archive_confirm': 'Archive this pair? It will be moved to the archive.',
    'agnosticism_pair_archived': 'Pair archived',
    'agnosticism_restore': 'Restore',
    'agnosticism_pair_restored': 'Pair restored',
    'agnosticism_max_pairs_error': 'Maximum 5 active pairs allowed. Archive one first.',
    'agnosticism_delete_title': 'Delete Pair',
    'agnosticism_delete_confirm': 'Permanently delete this pair? This cannot be undone.',
    'agnosticism_pair_deleted': 'Pair deleted',
    'agnosticism_archived_on': 'Archived on',
    // Help Content - 4th Step
    'help_4th_step_title': '4th Step Inventory - Purpose & Guidance',
    'help_4th_step_purpose_title': 'Why This Inventory?',
    'help_4th_step_purpose': 'The 4th Step asks us to make "a searching and fearless moral inventory." This tool helps identify resentments - the root of our spiritual illness. By examining what hurt us and our part in it, we prepare for freedom from the bondage of self.',
    'help_4th_step_fields_title': 'Understanding the Fields',
    'help_4th_step_fields': '• "I\'m resentful at" - The person, institution, or principle\n• "The Cause" - What they did or said that hurt\n• "Affects my" - Which part of self was threatened (self-esteem, security, ambitions, relationships, sex)\n• "My take" - Where was I selfish, dishonest, self-seeking, or frightened?\n• "Shortcomings" - Character defects revealed (fear, pride, anger, etc.)',
    'help_4th_step_i_am_title': 'The "I Am" Concept',
    'help_4th_step_i_am': '"I Am" definitions represent core identities tied to resentments (e.g., "I am the son", "I am the employee"). These help track patterns where specific roles trigger recurring character defects. This reveals which identities need spiritual realignment.',
    // Help Content - 8th Step
    'help_8th_step_title': '8th Step Amends List - Purpose & Guidance',
    'help_8th_step_purpose_title': 'Why Make This List?',
    'help_8th_step_purpose': 'Step 8 asks us to make "a list of all persons we had harmed, and became willing to make amends to them all." This prepares us for Step 9. Willingness, not action yet - we\'re building readiness to clean up our side of the street.',
    'help_8th_step_fields_title': 'Understanding the Columns',
    'help_8th_step_fields': '• Name - The person harmed\n• Column (optional) - Reference to 4th Step column (if resentment existed)\n• Amends Needed - What harm did I cause? What do I need to make right?\n• Amends Done - Track when you\'ve completed the 9th Step amend',
    // Help Content - Evening Ritual
    'help_evening_ritual_title': 'Evening Ritual - Purpose & Guidance',
    'help_evening_ritual_purpose_title': 'Why Review Each Day?',
    'help_evening_ritual_purpose': 'The Big Book (p.86) instructs: "Review the day. Were we resentful, selfish, dishonest or afraid?" This daily practice keeps us spiritually fit, catching defects quickly before they compound. Regular inventory prevents the build-up that leads to relapse.',
    'help_evening_ritual_reflection_types_title': 'The Ten Categories',
    'help_evening_ritual_reflection_types': 'Track daily where you:\n• Were resentful, selfish, dishonest, or afraid\n• Owe apologies or kept secrets\n• Showed kindness or could improve\n• Seek God\'s forgiveness\n• Plan corrective actions for tomorrow\n\nThese categories align with Big Book guidance for daily review.',
    'help_evening_ritual_focus_title': 'Self vs. Others Focus',
    'help_evening_ritual_focus': 'The slider tracks: "Where was my attention today?" Recovery shifts us from self-centeredness to being useful to others. Daily tracking reveals patterns - am I growing in selflessness or slipping into self-absorption?',
    // Help Content - Gratitude
    'help_gratitude_title': 'Gratitude Journal - Purpose & Guidance',
    'help_gratitude_purpose_title': 'Why Practice Gratitude?',
    'help_gratitude_purpose': 'Gratitude is the antidote to resentment and self-pity. The Big Book states we cannot be helpful when harboring resentment. Daily gratitude rewires our minds toward abundance rather than lack, shifting focus from what\'s wrong to what\'s right. This builds spiritual fitness.',
    'help_gratitude_practice_title': 'The Daily Practice',
    'help_gratitude_practice': 'Each day, record what you\'re grateful for using two fields: "Gratitude towards" (person, place, or thing) and "Grateful for" (what specifically about them). For example: towards "My sponsor" grateful for "Their patience and wisdom during my struggle." This structure helps you be specific and see patterns of grace in your life.',
    // Help Content - Agnosticism
    'help_agnosticism_title': 'Surrender & Correction - Purpose & Guidance',
    'help_agnosticism_purpose_title': 'Why This Exercise?',
    'help_agnosticism_purpose': 'This tool helps identify what we\'re still holding onto instead of surrendering to God, and the God-given corrective attitudes that replace our defects. It\'s a practical application of Step 3 - turning our will and lives over to the care of God.',
    'help_agnosticism_barriers_title': 'Not Given to God (Front Side)',
    'help_agnosticism_barriers': 'List what you haven\'t surrendered: resentments, fears, self-will, control, outcomes, relationships, finances, pride, etc. These are the things you\'re still trying to manage yourself instead of trusting God.',
    'help_agnosticism_powers_title': 'God-Given Corrective Attitude (Back Side)',
    'help_agnosticism_powers': 'For each thing not surrendered, identify the God-given attitude that corrects it: acceptance instead of control, trust instead of fear, humility instead of pride, gratitude instead of resentment, faith instead of worry.',
    'help_agnosticism_process_title': 'The Process',
    'help_agnosticism_process': 'Create up to 5 pairs. Each pair connects something you\'re holding onto with the corrective attitude God provides. Flip the paper to see both sides. When surrender happens and the attitude is adopted, archive the pair and add new ones as you grow.',
    // Morning Ritual
    'morning_ritual_title': 'Morning Ritual',
    'morning_ritual_today_tab': 'Today',
    'morning_ritual_history_tab': 'History',
    'morning_ritual_settings_desc': 'Define your morning ritual by adding timers and prayers. Drag to reorder.',
    'morning_ritual_no_items': 'No ritual items defined yet.\nTap + to add your first item.',
    'morning_ritual_add_item': 'Add Ritual Item',
    'morning_ritual_edit_item': 'Edit Ritual Item',
    'morning_ritual_delete_item': 'Delete Ritual Item',
    'morning_ritual_delete_confirm': 'Delete "%name%"? This cannot be undone.',
    'morning_ritual_item_name': 'Item Name',
    'morning_ritual_item_name_hint': 'e.g., 5 minute meditation, 3rd Step Prayer',
    'morning_ritual_item_type': 'Type',
    'morning_ritual_type_timer': 'Timer',
    'morning_ritual_type_prayer': 'Prayer',
    'morning_ritual_duration': 'Duration',
    'morning_ritual_minutes': 'Minutes',
    'morning_ritual_seconds': 'Seconds',
    'morning_ritual_prayer_text': 'Prayer Text',
    'morning_ritual_prayer_text_hint': 'Enter the prayer text to display',
    'morning_ritual_name_required': 'Name is required',
    'morning_ritual_ready': 'Ready to Begin',
    'morning_ritual_items_count': '%count% items in your ritual',
    'morning_ritual_start': 'Start Ritual',
    'morning_ritual_add_items_hint': 'Add items in the Settings tab first',
    'morning_ritual_no_items_to_start': 'No ritual items defined. Add items in Settings first.',
    'morning_ritual_timer_start': 'Start',
    'morning_ritual_timer_pause': 'Pause',
    'morning_ritual_timer_resume': 'Resume',
    'morning_ritual_timer_stop': 'Stop',
    'morning_ritual_skip': 'Skip',
    'morning_ritual_complete': 'Complete',
    'morning_ritual_completed': 'Morning ritual completed!',
    'morning_ritual_fully_completed': 'Fully Completed',
    'morning_ritual_partially_completed': 'Partially Completed',
    'morning_ritual_missed': 'Missed',
    'morning_ritual_completed_label': 'completed',
    'morning_ritual_skipped_label': 'skipped',
    'morning_ritual_missed_label': 'missed',
    'morning_ritual_status_completed': 'Completed',
    'morning_ritual_status_skipped': 'Skipped',
    'morning_ritual_status_missed': 'Missed',
    'morning_ritual_no_entry': 'No ritual entry for this date',
    'morning_ritual_select_date': 'Select a date to view details',
    'morning_ritual_no_history': 'No morning rituals yet',
    'morning_ritual_no_history_hint': 'Complete your first morning ritual to see your history here.',
    'morning_ritual_delete_entry': 'Delete Entry',
    'morning_ritual_delete_entry_confirm': 'Are you sure you want to delete the morning ritual entry for {date}?',
    'morning_ritual_entry_deleted': 'Entry deleted',
    'more': 'more',
    // Help Content - Morning Ritual
    'help_morning_ritual_title': 'Morning Ritual - Purpose & Guidance',
    'help_morning_ritual_purpose_title': 'Why a Morning Ritual?',
    'help_morning_ritual_purpose': 'The Big Book (p.86-88) describes the morning routine: "On awakening let us think about the twenty-four hours ahead... Before we begin, we ask God to direct our thinking." This tool helps establish a consistent morning practice of prayer and meditation.',
    'help_morning_ritual_items_title': 'Timers & Prayers',
    'help_morning_ritual_items': 'Create your ritual with two types of items:\n• Timers - For meditation or silent prayer (with alarm when complete)\n• Prayers - Display text for prayers like the 3rd Step, 7th Step, or St. Francis Prayer\n\nArrange items in the order you want to perform them.',
    'help_morning_ritual_practice_title': 'Daily Practice',
    'help_morning_ritual_practice': 'Each morning, start your ritual from the Today tab. Complete or skip each item as you go. Your history is tracked on the calendar - green checkmarks for completed items, red X for skipped or missed. Consistency builds spiritual discipline.',
  },
  'da': {
    'app_title': '4. Trins liste',
    'form_title': 'Form',
    'entries_title': 'Indtastninger',
    'settings_title': 'Indstillinger',
    'data_management': 'Datahåndtering',
    'export_json': 'Eksporter til JSON',
    'import_json': 'Importer fra JSON',
    'clear_all': 'Slet Alle Indtastninger',
    'cancel': 'Annuller',
    'confirm_clear': 'Dette vil permanent slette alle indtastninger. Fortsæt?',
    'delete_entry': 'Slet Indtastning',
    'delete_confirm': 'Er du sikker på, at du vil slette denne indtastning?',
    'delete': 'Slet',
    'edit_entry': 'Rediger Indtastning',
    'entry_deleted': 'Indtastning slettet',
    'my_take': 'Min(e) handling(er)',
    'shortcomings': 'Karakterdefekt(er)',
    'affect_my': 'Påvirker min',
    'i_am': 'Jeg er',
    'i_am_definitions': '"Jeg er" definitioner',
    'add_i_am': 'Tilføj "Jeg er"',
    'edit_i_am': 'Rediger "Jeg er"',
    'delete_i_am': 'Slet "Jeg er"',
    'i_am_name': '"Jeg er" navn',
    'reason': 'Årsag',
    'reason_to_exist_optional': 'Eksistensgrundlag',
    'select_i_am': 'Vælg Jeg er',
    'no_i_am_selected': 'Standard (ingen "Jeg er")',
    'confirm_delete_i_am': 'Slet denne "Jeg er" definition?',
    'i_am_name_required': '"Jeg er" navn er påkrævet',
    'search': 'Søg',
    'select_app': 'Vælg App',
    'switched_to_app': 'Skiftet til %s',
    'save_changes': 'Gem Ændringer',
    'add_entry': 'Tilføj Indtastning',
    'cancel_edit': 'Annuller Redigering',
    // App names and descriptions (Danish)
    'app_fourth_step_name': '4. trins liste',
    'app_fourth_step_desc': 'Opgørelse over nag',
    'app_eighth_step_name': '8. trins liste',
    'app_eighth_step_desc': 'Liste over folk vi skylder aflad',
    'app_evening_ritual_name': 'Aftenritual',
    'app_evening_ritual_desc': 'Daglig aftenrefleksion',
    'app_morning_ritual_name': 'Morgenritual',
    'app_morning_ritual_desc': 'Daglig morgen meditation og bønneroutine',
    'app_gratitude_name': 'Taknemmelighed',
    'app_gratitude_desc': 'Daglig taknemmeligheds dagbog',
    'app_agnosticism_name': 'Overgivelse & Korrektion',
    'app_agnosticism_desc': 'Hvad jeg ikke har overgivet & korrigerende holdninger',
    'googlefetch': 'Hent data fra Google Drive og overskriv lokale data',
    'sync_google_drive': 'Synkroniser med Google Drive',
    'sign_in_google': 'Log ind med Google',
    'sign_out_google': 'Log ud Google',
    'signed_in': 'Logget ind på Google',
    'signed_out': 'Logget ud',
    'enable_sync': 'Aktiver Synkronisering?',
    'enable_sync_prompt': 'Vil du aktivere automatisk Google Drive synkronisering for at holde dine data sikkerhedskopieret?',
    'not_now': 'Ikke Nu',
    'enable': 'Aktiver',
    'sync_complete': 'Synkronisering fuldført',
    'sync_failed': 'Synkronisering fejlede',
    'warning': 'Advarsel',
    'continue': 'Fortsæt',
    'export_success': 'Eksport fuldført',
    'drive_upload_success': 'Drive upload succes (%s indtastninger)',
    'no_entries': 'Ingen indtastninger',
    'confirm_google_fetch': 'Hent data fra Google Drive og overskriv lokale data?',
    'fetch': 'Hent',
    'fetching_data': 'Henter data fra Google Drive...',
    'select_restore_point': 'Vælg Gendannelsespunkt',
    'restore_point_latest': 'Seneste (Nuværende)',
    'restore_from_backup': 'Gendan fra Backup',
    'loading_backups': 'Indlæser backups...',
    'no_backups_available': 'Ingen backups tilgængelige',
    'part_tooltip': 'Har jeg været selvisk, uærlig, egoistisk eller skræmt?',
    'close': 'Luk',
    'edit': 'Rediger',
    'switch_app': 'Skift App',
    'refresh_backups': 'Opdater backups',
    'back_to_list': 'Tilbage til listen',
    'sign_in_to_enable_sync': 'Log ind med Google for at aktivere synkronisering',
    'cannot_delete_i_am_in_use': 'Kan ikke slette "%name%" fordi den bruges af %count% indtastninger.\n\nFjern eller ændr "Jeg er" for disse indtastninger først.',
    'resentment': 'Jeg er vred på',
    'switch_list_view': 'Skift til Listevisning',
    'switch_table_view': 'Skift til Tabelvisning',
    // Error and status messages
    'failed_load_backups': 'Kunne ikke indlæse backups',
    'sign_in_no_token': 'Google login lykkedes, men ingen adgangstoken blev returneret',
    'drive_init_failed': 'Drive initialisering fejlede',
    'drive_not_available': 'Google Drive synkronisering ikke tilgængelig',
    'fetch_failed': 'Hentning fejlede',
    'json_saved': 'JSON gemt i',
    'export_failed': 'Eksport fejlede',
    'import_failed': 'Import fejlede',
    'import_success': 'Importerede %d indtastninger, %d "Jeg er" definitioner, %d personer, %d refleksioner',
    'fetch_success': 'Hentet fra Google Drive',
    'sign_in_failed': 'Login fejlede',
    'sign_in_cancelled': 'Login fejlede eller blev annulleret',
    'no_data_found': 'Ingen data fundet i Google Drive',
    'fetch_success_count': 'Hentede %entries% indtastninger, %iams% "Jeg er" definitioner fra Google Drive',
    'no_entries_found': 'Ingen indtastninger fundet i Google Drive',
    'offline_backups': 'Offline Backups',
    'save_json_export': 'Gem JSON Eksport',
    'export_data': 'Eksporter Data',
    'help': 'Hjælp',
    'information': 'Information',
    'help_not_available': 'Hjælpeindhold ikke tilgængeligt for denne app.',
    'clear_warning': 'Dette vil slette alle data permanent. Fortsæt?',
    'clear': 'Slet',
    'all_cleared': 'Alle data slettet',
    'import_success_count': 'Importerede %entries% indtastninger, %iams% "Jeg er" definitioner, %people% personer, %reflections% refleksioner',
    // Language names (keep as-is, these are proper nouns)
    'lang_english': 'English',
    'lang_danish': 'Dansk',
    // 8th Step Amends
    'eighth_step_title': '8. Trins liste',
    'eighth_step_main_tab': 'Liste',
    'eighth_step_view_tab': 'Vis',
    'eighth_step_yes': 'Ja',
    'eighth_step_no': 'Nej',
    'eighth_step_maybe': 'Måske',
    'add_person': 'Tilføj Person',
    'edit_person': 'Rediger Person',
    'delete_person': 'Slet Person',
    'person_name': 'Navn',
    'amends': 'Aflad',
    'amends_needed': '9. trins aflad nødvendigt',
    'amends_done': '9. trin fuldført',
    'amends_done_question': '9. trin fuldført?',
    'column': 'Kolonne',
    'enter_name': 'Indtast navn',
    'enter_amends': '9. trins aflad',
    'confirm_delete_person': 'Slet denne person?',
    'person_name_required': 'Navn er påkrævet',
    'optional': 'Valgfrit',
    'select_person_prompt': 'Vælg en person fra Listen',
    'import_from_drive': 'Importer fra Google Drive',
    'import': 'Importer',
    'upload_to_drive_manual': 'Upload til Google Drive (Manuel)',
    'google_authorization': 'Google Godkendelse',
    'copied_url': 'Jeg har kopieret URL\'en',
    'import_warning': 'Dette vil ERSTATTE alle nuværende data med data fra Google Drive.\n\nSørg for at du først har eksporteret dine nuværende data!\n\nFortsæt med import?',
    // Evening Ritual (Danish)
    'evening_ritual_title': 'Aftenritual',
    'evening_ritual_form_tab': 'I dag',
    'evening_ritual_list_tab': 'Historik',
    'reflection_type_resentful': 'Jeg var vred på',
    'reflection_type_selfish': 'Jeg var selvisk da',
    'reflection_type_dishonest': 'Jeg var uærlig da',
    'reflection_type_afraid': 'Jeg var bange da',
    'reflection_type_apology_owed': 'Jeg skylder en undskyldning til',
    'reflection_type_kept_to_myself': 'Jeg holdt for mig selv (hvor jeg burde have delt)',
    'reflection_type_kind_loving': 'Jeg var venlig og kærlig overfor',
    'reflection_type_could_do_better': 'Jeg kunne have gjort det bedre ved',
    'reflection_type_gods_forgiveness': 'Guds tilgivelse (hvad jeg beder om)',
    'reflection_type_corrective_measures': 'Korrigerende handlinger (hvad vil jeg gøre i morgen)',
    'add_reflection': 'Tilføj Refleksion',
    'edit_reflection': 'Rediger Refleksion',
    'reflection_detail': 'Detalje',
    'thinking_focus_question': 'Hvor var min opmærksomhed rettet i dag?',
    'thinking_self': 'Tænker på mig selv',
    'thinking_others': 'Tænker på andre',
    'slider_completely_self': 'Fuldstændig Selvfokuseret',
    'slider_mostly_self': 'Mest Selvfokuseret',
    'slider_leaning_self': 'Hælder til Selvfokuseret',
    'slider_balanced': 'Afbalanceret',
    'slider_leaning_others': 'Hælder til fokus på andre',
    'slider_mostly_others': 'Mest fokuseret på andre',
    'slider_completely_others': 'Fuldstændig fokuseret på andre',
    'save_reflection': 'Gem',
    'reflection_saved': 'Refleksion gemt',
    'no_reflections': 'Ingen refleksioner endnu',
    'no_reflections_hint': 'Tryk på kalenderen for at tilføje din første aftenrefleksion',
    'reflection_entries_count': '%d indtastninger',
    'delete_reflection': 'Slet Refleksion',
    'delete_reflection_confirm': 'Slet denne refleksion?',
    'reflection_deleted': 'Refleksion slettet',
    'select_reflection_type': 'Vælg refleksionstype',
    'past_date_read_only': 'Denne dato er i fortiden og kan ikke redigeres. Kun dagens indtastning kan ændres.',
    'delete_day': 'Slet Alle Refleksioner',
    'confirm_delete_day': 'Slet alle {count} refleksioner for {date}?',
    'day_deleted': 'Alle refleksioner slettet',
    // Gratitude (Danish)
    'gratitude_title': 'Taknemmelighed',
    'gratitude_today_tab': 'I dag',
    'gratitude_view_tab': 'Vis',
    'gratitude_today_subtitle': 'Hvad er du taknemmelig for i dag?',
    'gratitude_add_entry': 'Tilføj Taknemmelighed',
    'gratitude_edit_entry': 'Rediger Taknemmelighed',
    'gratitude_towards_label': 'Taknemmelighed over for',
    'gratitude_towards_hint': 'Person, sted eller ting',
    'gratitude_for_label': 'Taknemmelig for',
    'gratitude_for_hint': 'Hvad ved dem er du taknemmelig for?',
    'gratitude_no_entries': 'Ingen taknemmeligheds-indlæg endnu',
    'gratitude_no_entries_today': 'Ingen taknemmeligheds indtastninger for i dag',
    'gratitude_no_entries_hint': 'Start din taknemmeligheds dagbog i I dag fanen',
    'gratitude_entries_count': '%d indtastninger',
    'gratitude_delete_title': 'Slet Taknemmelighed',
    'gratitude_delete_confirm': 'Slet denne taknemmeligheds indtastning?',
    'update': 'Opdater',
    'add': 'Tilføj',
    // Agnosticism (Danish)
    'agnosticism_title': 'Overgivelse & Korrektion',
    'agnosticism_paper_tab': 'Papir',
    'agnosticism_archive_tab': 'Arkiv',
    'agnosticism_barriers_title': 'Ikke Overgivet til Gud (Forside)',
    'agnosticism_powers_title': 'Gudgiven Korrigerende Holdning (Bagside)',
    'agnosticism_flip': 'Vend Papir',
    'agnosticism_add_pair': 'Tilføj Par',
    'agnosticism_edit_pair': 'Rediger Par',
    'agnosticism_empty_paper': 'Ingen par endnu.\nTryk "Tilføj Par" for at starte.',
    'agnosticism_empty_archive': 'Ingen arkiverede par endnu',
    'agnosticism_barrier': 'Ikke Overgivet',
    'agnosticism_power': 'Korrigerende Holdning',
    'agnosticism_barrier_hint': 'Hvad har jeg ikke overgivet til Gud?',
    'agnosticism_power_hint': 'Hvilken gudgiven holdning korrigerer dette?',
    'agnosticism_barrier_required': 'Dette felt er påkrævet',
    'agnosticism_power_required': 'Dette felt er påkrævet',
    'agnosticism_update': 'Opdater',
    'agnosticism_add': 'Tilføj',
    'agnosticism_archive': 'Arkivér',
    'agnosticism_archive_title': 'Arkivér Par',
    'agnosticism_archive_confirm': 'Arkivér dette par? Det flyttes til arkivet.',
    'agnosticism_pair_archived': 'Par arkiveret',
    'agnosticism_restore': 'Gendan',
    'agnosticism_pair_restored': 'Par gendannet',
    'agnosticism_max_pairs_error': 'Maksimalt 5 aktive par tilladt. Arkivér et først.',
    'agnosticism_delete_title': 'Slet Par',
    'agnosticism_delete_confirm': 'Slet dette par permanent? Dette kan ikke fortrydes.',
    'agnosticism_pair_deleted': 'Par slettet',
    'agnosticism_archived_on': 'Arkiveret den',
    // Help Content - 4th Step (Danish)
    'help_4th_step_title': '4. Trins opgørelse - Formål & Vejledning',
    'help_4th_step_purpose_title': 'Hvorfor denne opgørelse',
    'help_4th_step_purpose': '4. Trin beder os om at lave "en grundig og frygtløs moralsk opgørelse over alt hvad vi indeholder." Dette værktøj hjælper med at identificere hvad vi indeholder - og afdække grundenene til vores åndelige men. Ved at undersøge hvad der påvirkede os og vores rolle i det, forbereder vi os til frihed fra selvets lænker.',
    'help_4th_step_fields_title': 'Forståelse af Felterne',
    'help_4th_step_fields': '• "Jeg er vred på" - Personen, institutionen eller princippet\n• "Årsagen" - Hvad de gjorde eller sagde der sårede\n• "Påvirker min" - Hvilken del af selvet blev truet (selvværd, sikkerhed, ambitioner, relationer, sex)\n• "Min(e) handling(er)" - Hvor var jeg selvisk, uærlig, egoistisk eller skræmt?\n• "Karakterdefekt(er)" - Afslørede karakterfejl (frygt, stolthed, vrede osv.)',
    'help_4th_step_i_am_title': '"Jeg Er" Konceptet',
    'help_4th_step_i_am': '"Jeg er" definitioner repræsenterer kerneidentiteter knyttet til årsagen (f.eks. "Jeg er sønnen", "Jeg er medarbejderen"). Disse hjælper med at spore mønstre, hvor specifikke roller udløser tilbagevendende karakterdefekter. Dette afslører hvilke identiteter der har brug for åndelig tilpasning.',
    // Help Content - 8th Step (Danish)
    'help_8th_step_title': '8. Trins liste - Formål & Vejledning',
    'help_8th_step_purpose_title': 'Hvorfor lave denne liste?',
    'help_8th_step_purpose': 'Trin 8 beder os om at lave "en liste over alle personer vi har gjort fortræd, og blive villige til at gøre det godt igen. Med listen, forbereder os til trin 9. - vi bygger parathed og villighed til at rydde op og tage ansvar for vores del.',
    'help_8th_step_fields_title': 'Forståelse af Kolonnerne',
    'help_8th_step_fields': '• Navn - Den person vi har gjort fortræd\n• Kolonne (valgfrit)\n• 9. trin nødvendigt - Hvilken skade forvoldte jeg? Hvad skal jeg gøre godt igen?\n• 9. trin fuldført - når du har fuldført 9. trin',
    // Help Content - Evening Ritual (Danish)
    'help_evening_ritual_title': 'Aftenritual - Formål & Vejledning',
    'help_evening_ritual_purpose_title': 'Hvorfor Gennemgå Hver Dag?',
    'help_evening_ritual_purpose': 'Den Store Bog (s.86) instruerer: "Gennemgå dagen. Var vi vrede, selviske, uærlige eller bange?" Denne daglige praksis holder os åndeligt fit, fanger fejl hurtigt før de forværres. Regelmæssig inventar forhindrer opbygning der fører til tilbagefald.',
    'help_evening_ritual_reflection_types_title': 'De Ti Kategorier',
    'help_evening_ritual_reflection_types': 'Spor dagligt hvor du:\n• Var vred, selvisk, uærlig eller bange\n• Skylder undskyldninger eller holdt hemmeligheder\n• Viste venlighed eller kunne forbedre\n• Søger Guds tilgivelse\n• Planlæg korrigerende handlinger for i morgen\n\nDisse kategorier stemmer overens med Den Store Bogs vejledning for daglig gennemgang.',
    'help_evening_ritual_focus_title': 'Selv vs. Andre Fokus',
    'help_evening_ritual_focus': 'Skyderen sporer: "Hvor var min opmærksomhed i dag?" Bedring flytter os fra selvcentrering til at være nyttige for andre. Daglig sporing afslører mønstre - vokser jeg i uselviskhed eller glider jeg ind i selvoptagethed?',
    // Help Content - Gratitude (Danish)
    'help_gratitude_title': 'Taknemmeligheds Dagbog - Formål & Vejledning',
    'help_gratitude_purpose_title': 'Hvorfor Øve Taknemmelighed?',
    'help_gratitude_purpose': 'Taknemmelighed er modgiften mod vrede og selvmedlidenhed. Den Store Bog siger vi ikke kan være hjælpsomme når vi nærer vrede. Daglig taknemmelighed omkobler vores sind mod overflod frem for mangel, flytter fokus fra hvad der er galt til hvad der er rigtigt. Dette bygger åndelig fitness.',
    'help_gratitude_practice_title': 'Den Daglige Praksis',
    'help_gratitude_practice': 'Hver dag, noter hvad du er taknemmelig for ved hjælp af to felter: "Taknemmelighed over for" (person, sted eller ting) og "Taknemmelig for" (hvad specifikt ved dem). For eksempel: over for "Min sponsor" taknemmelig for "Deres tålmodighed og visdom under min kamp." Denne struktur hjælper dig med at være specifik og se mønstre af nåde i dit liv.',
    // Help Content - Agnosticism (Danish)
    'help_agnosticism_title': 'Overgivelse & Korrektion - Formål & Vejledning',
    'help_agnosticism_purpose_title': 'Hvorfor Denne Øvelse?',
    'help_agnosticism_purpose': 'Dette værktøj hjælper med at identificere hvad vi stadig holder fast i i stedet for at overgive det til Gud, og de gudgivne korrigerende holdninger der erstatter vores defekter. Det er en praktisk anvendelse af trin 3 - at overlade vores vilje og liv til Guds omsorg.',
    'help_agnosticism_barriers_title': 'Ikke Overgivet til Gud (Forside)',
    'help_agnosticism_barriers': 'List hvad du ikke har overgivet: vrede, frygt, egenvilje, kontrol, resultater, relationer, økonomi, stolthed osv. Dette er de ting du stadig prøver at styre selv i stedet for at stole på Gud.',
    'help_agnosticism_powers_title': 'Gudgiven Korrigerende Holdning (Bagside)',
    'help_agnosticism_powers': 'For hver ting der ikke er overgivet, identificer den gudgivne holdning der korrigerer den: accept i stedet for kontrol, tillid i stedet for frygt, ydmyghed i stedet for stolthed, taknemmelighed i stedet for vrede, tro i stedet for bekymring.',
    'help_agnosticism_process_title': 'Processen',
    'help_agnosticism_process': 'Opret op til 5 par. Hvert par forbinder noget du holder fast i med den korrigerende holdning Gud giver. Vend papiret for at se begge sider. Når overgivelsen sker og holdningen er adopteret, arkivér parret og tilføj nye efterhånden som du vokser.',
    // Morning Ritual (Danish)
    'morning_ritual_title': 'Morgenritual',
    'morning_ritual_today_tab': 'I dag',
    'morning_ritual_history_tab': 'Historik',
    'morning_ritual_settings_desc': 'Definer dit morgenritual ved at tilføje timere og bønner. Træk for at omarrangere.',
    'morning_ritual_no_items': 'Ingen ritualelementer defineret endnu.\nTryk + for at tilføje dit første element.',
    'morning_ritual_add_item': 'Tilføj Ritualelement',
    'morning_ritual_edit_item': 'Rediger Ritualelement',
    'morning_ritual_delete_item': 'Slet Ritualelement',
    'morning_ritual_delete_confirm': 'Slet "%name%"? Dette kan ikke fortrydes.',
    'morning_ritual_item_name': 'Elementnavn',
    'morning_ritual_item_name_hint': 'f.eks. 5 minutters meditation, 3. trins bøn',
    'morning_ritual_item_type': 'Type',
    'morning_ritual_type_timer': 'Timer',
    'morning_ritual_type_prayer': 'Bøn',
    'morning_ritual_duration': 'Varighed',
    'morning_ritual_minutes': 'Minutter',
    'morning_ritual_seconds': 'Sekunder',
    'morning_ritual_prayer_text': 'Bøn',
    'morning_ritual_prayer_text_hint': 'Indtast teksten på bønnen, der skal vises',
    'morning_ritual_name_required': 'Navn er påkrævet',
    'morning_ritual_ready': 'Klar til at Begynde',
    'morning_ritual_items_count': '%count% elementer i dit ritual',
    'morning_ritual_start': 'Start Ritual',
    'morning_ritual_add_items_hint': 'Tilføj elementer i Indstillinger først',
    'morning_ritual_no_items_to_start': 'Ingen ritualelementer defineret. Tilføj elementer i Indstillinger først.',
    'morning_ritual_timer_start': 'Start',
    'morning_ritual_timer_pause': 'Pause',
    'morning_ritual_timer_resume': 'Genoptag',
    'morning_ritual_timer_stop': 'Stop',
    'morning_ritual_skip': 'Spring over',
    'morning_ritual_complete': 'Fuldfør',
    'morning_ritual_completed': 'Morgenritual fuldført!',
    'morning_ritual_fully_completed': 'Fuldt Fuldført',
    'morning_ritual_partially_completed': 'Delvist Fuldført',
    'morning_ritual_missed': 'Misset',
    'morning_ritual_completed_label': 'fuldført',
    'morning_ritual_skipped_label': 'sprunget over',
    'morning_ritual_missed_label': 'misset',
    'morning_ritual_status_completed': 'Fuldført',
    'morning_ritual_status_skipped': 'Sprunget over',
    'morning_ritual_status_missed': 'Misset',
    'morning_ritual_no_entry': 'Ingen ritualindgang for denne dato',
    'morning_ritual_select_date': 'Vælg en dato for at se detaljer',
    'morning_ritual_no_history': 'Ingen morgenritualer endnu',
    'morning_ritual_no_history_hint': 'Fuldfør dit første morgenritual for at se din historik her.',
    'morning_ritual_delete_entry': 'Slet indtastning',
    'morning_ritual_delete_entry_confirm': 'Er du sikker på, at du vil slette morgenritual for {date}?',
    'morning_ritual_entry_deleted': 'Indtastning slettet',
    'more': 'mere',
    // Help Content - Morning Ritual (Danish)
    'help_morning_ritual_title': 'Morgenritual - Formål & Vejledning',
    'help_morning_ritual_purpose_title': 'Hvorfor et Morgenritual?',
    'help_morning_ritual_purpose': 'Den Store Bog (s.86-88) beskriver morgenrutinen: "Ved opvågning lad os tænke på de fireogtyve timer forude... Før vi begynder, beder vi Gud om at lede vores tankegang." Dette værktøj hjælper med at etablere en konsistent morgenpraksis med bøn og meditation.',
    'help_morning_ritual_items_title': 'Timere & Bønner',
    'help_morning_ritual_items': 'Opret dit ritual med to typer elementer:\n• Timere - Til meditation eller stille bøn (med alarm når færdig)\n• Bønner - Vis tekst til bønner som 3. trins, 7. trins eller St. Frans bønnen\n\nArranger elementer i den rækkefølge du vil udføre dem.',
    'help_morning_ritual_practice_title': 'Daglig Praksis',
    'help_morning_ritual_practice': 'Hver morgen, start dit ritual fra I dag fanen. Fuldfør eller spring over hvert element. Din historik spores på kalenderen - grønne flueben for fuldførte elementer, rødt X for sprunget over eller misset. Konsistens bygger åndelig disciplin.',
  },
};

String t(BuildContext context, String key) {
  final locale = Localizations.localeOf(context);
  return localizedValues[locale.languageCode]?[key] ??
      localizedValues['en']?[key] ??
      key; // fallback to key itself
}
