import 'package:flutter/material.dart';

final Map<String, Map<String, String>> localizedValues = {
  'en': {
    'app_title': '4th Step Inventory',
    'form_title': 'Form',
    'entries_title': 'Entries',
    'settings_title': 'Settings',
    'data_management': 'Data Management',
    'export_json': 'Export to JSON',
    'import_json': 'Import from JSON',
    'clear_all': 'Clear All Entries',
    'cancel': 'Cancel',
    'confirm_clear': 'This will delete all entries permanently. Continue?',
    'delete_entry': 'Delete Entry',
    'delete_confirm': 'Are you sure you want to delete this entry?',
    'delete': 'Delete',
    'edit_entry': 'Edit Entry',
    'entry_deleted': 'Entry deleted successfully',
    'my_take': 'My take',
    'shortcomings': 'Shortcommings',
    'affect_my': 'Affects my',
    'i_am': 'I Am',
    'i_am_definitions': 'I Am Definitions',
    'add_i_am': 'Add I Am',
    'edit_i_am': 'Edit I Am',
    'delete_i_am': 'Delete I Am',
    'i_am_name': 'I Am name',
    'reason': 'The Cause',
    'reason_to_exist_optional': 'Reason to exist',
    'select_i_am': 'Select I Am',
    'no_i_am_selected': 'Standard (no I Am)',
    'confirm_delete_i_am': 'Delete this I Am definition?',
    'i_am_name_required': 'I Am name is required',
    'search': 'Search',
    'save_changes': 'Save Changes',
    'add_entry': 'Add Entry',
    'cancel_edit': 'Cancel Edit',
    'googlefetch': 'Fetch data from Google Drive and overwrite local data',
    'sync_google_drive': 'Sync with Google Drive',
    'drive_upload_success': 'Drive upload successful (%s entries)',
    'no_entries': 'No entries',
    'confirm_google_fetch': 'Fetch data from Google Drive and overwrite local data?',
    'fetch': 'Fetch',
    'fetching_data': 'Fetching data from Google Drive...',
    'part_tooltip': 'Have I been Selfish, dishonest, self-seeking or frightened?',
    'close': 'Close',
    'resentment': 'I\'m resentful at',
    'switch_list_view': 'Switch to List View',
    'switch_table_view': 'Switch to Table View',
    // 8th Step Amends
    'eighth_step_title': '8th Step list',
    'eighth_step_main_tab': 'Main',
    'eighth_step_view_tab': 'View',
    'eighth_step_yes': 'Yes',
    'eighth_step_no': 'No',
    'eighth_step_maybe': 'Maybe',
    'add_person': 'Add Person',
    'edit_person': 'Edit Person',
    'delete_person': 'Delete Person',
    'person_name': 'Name',
    'amends': 'Amends',
    'amends_needed': 'Amends Needed',
    'amends_done': 'Amends Done',
    'amends_done_question': 'Amends Done?',
    'column': 'Column',
    'enter_name': 'Enter name',
    'enter_amends': 'Enter amends needed',
    'confirm_delete_person': 'Delete this person?',
    'person_name_required': 'Name is required',
    'optional': 'Optional',
    // Evening Ritual
    'evening_ritual_title': 'Evening Ritual',
    'evening_ritual_form_tab': 'Today',
    'evening_ritual_list_tab': 'History',
    'reflection_type_resentful': 'I was resentful towards',
    'reflection_type_selfish': 'I was selfish when',
    'reflection_type_dishonest': 'I was dishonest when',
    'reflection_type_afraid': 'I was afraid when',
    'reflection_type_apology_owed': 'I owe an apology to',
    'reflection_type_kept_to_myself': 'I kept to myself (should have shared)',
    'reflection_type_kind_loving': 'I was kind and loving toward',
    'reflection_type_could_do_better': 'I could have done better by',
    'reflection_type_gods_forgiveness': 'God\'s forgiveness (what I ask for)',
    'reflection_type_corrective_measures': 'Corrective measures (what will I do tomorrow)',
    'add_reflection': 'Add Reflection',
    'edit_reflection': 'Edit Reflection',
    'reflection_detail': 'Detail',
    'thinking_focus_question': 'Where was my attention focused today?',
    'thinking_self': 'Thinking of myself',
    'thinking_others': 'Thinking of others',
    'slider_completely_self': 'Completely Self-Focused',
    'slider_mostly_self': 'Mostly Self-Focused',
    'slider_leaning_self': 'Leaning Self-Focused',
    'slider_balanced': 'Balanced',
    'slider_leaning_others': 'Leaning Others-Focused',
    'slider_mostly_others': 'Mostly Others-Focused',
    'slider_completely_others': 'Completely Others-Focused',
    'save_reflection': 'Save',
    'reflection_saved': 'Reflection saved',
    'no_reflections': 'No reflections yet',
    'no_reflections_hint': 'Tap the calendar to add your first evening reflection',
    'reflection_entries_count': '%d entries',
    'delete_reflection': 'Delete Reflection',
    'delete_reflection_confirm': 'Delete this reflection?',
    'reflection_deleted': 'Reflection deleted',
    'select_reflection_type': 'Select reflection type',
    'past_date_read_only': 'This date is in the past and cannot be edited. Only today\'s entry can be modified.',
    'delete_day': 'Delete All Reflections',
    'confirm_delete_day': 'Delete all {count} reflections for {date}?',
    'day_deleted': 'All reflections deleted',
    // Gratitude
    'gratitude_title': 'Gratitude',
    'gratitude_today_tab': 'Today',
    'gratitude_view_tab': 'View',
    'gratitude_today_subtitle': 'What are you grateful for today?',
    'gratitude_add_entry': 'Add Gratitude',
    'gratitude_edit_entry': 'Edit Gratitude',
    'gratitude_towards_label': 'Gratitude towards',
    'gratitude_towards_hint': 'What are you grateful for today?',
    'gratitude_no_entries': 'No gratitude entries yet',
    'gratitude_no_entries_today': 'No gratitude entries for today',
    'gratitude_no_entries_hint': 'Start your gratitude journal in the Today tab',
    'gratitude_entries_count': '%d entries',
    'gratitude_delete_title': 'Delete Gratitude',
    'gratitude_delete_confirm': 'Delete this gratitude entry?',
    'update': 'Update',
    'add': 'Add',
  },
  'da': {
    'app_title': '4. Trins Inventory',
    'form_title': 'Form',
    'entries_title': 'Indtastninger',
    'settings_title': 'Indstillinger',
    'data_management': 'Data Håndtering',
    'export_json': 'Eksporter til JSON',
    'import_json': 'Importer fra JSON',
    'clear_all': 'Slet Alle Indtastninger',
    'cancel': 'Annuller',
    'confirm_clear': 'Dette vil permanent slette alle indtastninger. Fortsæt?',
    'delete_entry': 'Slet Indtastning',
    'delete_confirm': 'Er du sikker på, at du vil slette denne indtastning?',
    'delete': 'Slet',
    'edit_entry': 'Rediger Indtastning',
    'entry_deleted': 'Indtastning slettet',
    'my_take': 'Min(e) handling(er)',
    'shortcomings': 'Karakterdefekt(er)',
    'affect_my': 'Påvirker min',
    'i_am': 'Jeg er',
    'i_am_definitions': 'Jeg er definitioner',
    'add_i_am': 'Tilføj Jeg er',
    'edit_i_am': 'Rediger Jeg er',
    'delete_i_am': 'Slet Jeg er',
    'i_am_name': 'Jeg er navn',
    'reason': 'Årsag',
    'reason_to_exist_optional': 'Eksistensgrundlag',
    'select_i_am': 'Vælg Jeg er',
    'no_i_am_selected': 'Standard (ingen Jeg er)',
    'confirm_delete_i_am': 'Slet denne Jeg er definition?',
    'i_am_name_required': 'Jeg er navn er påkrævet',
    'search': 'Søg',
    'save_changes': 'Gem Ændringer',
    'add_entry': 'Tilføj Indtastning',
    'cancel_edit': 'Annuller Redigering',
    'googlefetch': 'Hent data fra Google Drive og overskriv lokale data',
    'sync_google_drive': 'Synkroniser med Google Drive',
    'drive_upload_success': 'Drive upload succes (%s indtastninger)',
    'no_entries': 'Ingen indtastninger',
    'confirm_google_fetch': 'Hent data fra Google Drive og overskriv lokale data?',
    'fetch': 'Hent',
    'fetching_data': 'Henter data fra Google Drive...',
    'part_tooltip': 'Har jeg været selvisk, uærlig, egoistisk eller skræmt?',
    'close': 'Luk',
    'resentment': 'Jeg er vred på',
    'switch_list_view': 'Skift til Listevisning',
    'switch_table_view': 'Skift til Tabelvisning',
    // 8th Step Amends
    'eighth_step_title': '8. Trins liste',
    'eighth_step_main_tab': 'Liste',
    'eighth_step_view_tab': 'Vis',
    'eighth_step_yes': 'Ja',
    'eighth_step_no': 'Nej',
    'eighth_step_maybe': 'Måske',
    'add_person': 'Tilføj Person',
    'edit_person': 'Rediger Person',
    'delete_person': 'Slet Person',
    'person_name': 'Navn',
    'amends': 'Erstatning',
    'amends_needed': '9. trin',
    'amends_done': '9. trin fuldført',
    'amends_done_question': '9. trin fuldført?',
    'column': 'Kolonne',
    'enter_name': 'Indtast navn',
    'enter_amends': '9. trin',
    'confirm_delete_person': 'Slet denne person?',
    'person_name_required': 'Navn er påkrævet',
    'optional': 'Valgfrit',
    // Evening Ritual (Danish)
    'evening_ritual_title': 'Aftenritual',
    'evening_ritual_form_tab': 'I dag',
    'evening_ritual_list_tab': 'Historik',
    'reflection_type_resentful': 'Jeg var vred på',
    'reflection_type_selfish': 'Jeg var selvisk da',
    'reflection_type_dishonest': 'Jeg var uærlig da',
    'reflection_type_afraid': 'Jeg var bange da',
    'reflection_type_apology_owed': 'Jeg skylder en undskyldning til',
    'reflection_type_kept_to_myself': 'Jeg holdt for mig selv (burde have delt)',
    'reflection_type_kind_loving': 'Jeg var venlig og kærlig overfor',
    'reflection_type_could_do_better': 'Jeg kunne have gjort det bedre ved',
    'reflection_type_gods_forgiveness': 'Guds tilgivelse (hvad jeg beder om)',
    'reflection_type_corrective_measures': 'Korrigerende handlinger (hvad vil jeg gøre i morgen)',
    'add_reflection': 'Tilføj Refleksion',
    'edit_reflection': 'Rediger Refleksion',
    'reflection_detail': 'Detalje',
    'thinking_focus_question': 'Hvor var min opmærksomhed fokuseret i dag?',
    'thinking_self': 'Tænker på mig selv',
    'thinking_others': 'Tænker på andre',
    'slider_completely_self': 'Fuldstændig Selvfokuseret',
    'slider_mostly_self': 'Mest Selvfokuseret',
    'slider_leaning_self': 'Hælder til Selvfokuseret',
    'slider_balanced': 'Afbalanceret',
    'slider_leaning_others': 'Hælder til Andrefokuseret',
    'slider_mostly_others': 'Mest Andrefokuseret',
    'slider_completely_others': 'Fuldstændig Andrefokuseret',
    'save_reflection': 'Gem',
    'reflection_saved': 'Refleksion gemt',
    'no_reflections': 'Ingen refleksioner endnu',
    'no_reflections_hint': 'Tryk på kalenderen for at tilføje din første aftenrefleksion',
    'reflection_entries_count': '%d indtastninger',
    'delete_reflection': 'Slet Refleksion',
    'delete_reflection_confirm': 'Slet denne refleksion?',
    'reflection_deleted': 'Refleksion slettet',
    'select_reflection_type': 'Vælg refleksionstype',
    'past_date_read_only': 'Denne dato er i fortiden og kan ikke redigeres. Kun dagens indtastning kan ændres.',
    'delete_day': 'Slet Alle Refleksioner',
    'confirm_delete_day': 'Slet alle {count} refleksioner for {date}?',
    'day_deleted': 'Alle refleksioner slettet',
    // Gratitude (Danish)
    'gratitude_title': 'Taknemmelighed',
    'gratitude_today_tab': 'I dag',
    'gratitude_view_tab': 'Vis',
    'gratitude_today_subtitle': 'Hvad er du taknemmelig for i dag?',
    'gratitude_add_entry': 'Tilføj Taknemmelighed',
    'gratitude_edit_entry': 'Rediger Taknemmelighed',
    'gratitude_towards_label': 'Taknemmelig for',
    'gratitude_towards_hint': 'Hvad er du taknemmelig for i dag?',
    'gratitude_no_entries': 'Ingen taknemmeligheds indtastninger endnu',
    'gratitude_no_entries_today': 'Ingen taknemmeligheds indtastninger for i dag',
    'gratitude_no_entries_hint': 'Start din taknemmeligheds dagbog i I dag fanen',
    'gratitude_entries_count': '%d indtastninger',
    'gratitude_delete_title': 'Slet Taknemmelighed',
    'gratitude_delete_confirm': 'Slet denne taknemmeligheds indtastning?',
    'update': 'Opdater',
    'add': 'Tilføj',
  },
};

String t(BuildContext context, String key) {
  final locale = Localizations.localeOf(context);
  return localizedValues[locale.languageCode]?[key] ??
      localizedValues['en']?[key] ??
      key; // fallback to key itself
}
