import 'package:flutter/material.dart';

final Map<String, Map<String, String>> localizedValues = {
  'en': {
    'app_title': '4th Step Inventory',
    'form_title': 'Form',
    'entries_title': 'Entries',
    'settings_title': 'Settings',
    'data_management': 'Data Management',
    'export_json': 'Export to JSON',
    'import_json': 'Import from JSON',
    'clear_all': 'Clear All Entries',
    'cancel': 'Cancel',
    'confirm_clear': 'This will delete all entries permanently. Continue?',
    'delete_entry': 'Delete Entry',
    'delete_confirm': 'Are you sure you want to delete this entry?',
    'delete': 'Delete',
    'edit_entry': 'Edit Entry',
    'entry_deleted': 'Entry deleted successfully',
    'my_take': 'My take',
    'shortcomings': 'Shortcommings',
    'affect_my': 'Affects my',
    'i_am': 'I Am',
    'i_am_definitions': 'I Am Definitions',
    'add_i_am': 'Add I Am',
    'edit_i_am': 'Edit I Am',
    'delete_i_am': 'Delete I Am',
    'i_am_name': 'I Am name',
    'reason': 'The Cause',
    'reason_to_exist_optional': 'Reason to exist',
    'select_i_am': 'Select I Am',
    'no_i_am_selected': 'Standard (no I Am)',
    'confirm_delete_i_am': 'Delete this I Am definition?',
    'i_am_name_required': 'I Am name is required',
    'search': 'Search',
    'save_changes': 'Save Changes',
    'add_entry': 'Add Entry',
    'cancel_edit': 'Cancel Edit',
    'googlefetch': 'Fetch data from Google Drive and overwrite local data',
    'sync_google_drive': 'Sync with Google Drive',
    'drive_upload_success': 'Drive upload successful (%s entries)',
    'no_entries': 'No entries',
    'confirm_google_fetch': 'Fetch data from Google Drive and overwrite local data?',
    'fetch': 'Fetch',
    'fetching_data': 'Fetching data from Google Drive...',
    'select_restore_point': 'Select Restore Point',
    'restore_point_latest': 'Latest (Current)',
    'restore_from_backup': 'Restore from Backup',
    'loading_backups': 'Loading backups...',
    'no_backups_available': 'No backups available',
    'part_tooltip': 'Have I been Selfish, dishonest, self-seeking or frightened?',
    'close': 'Close',
    'resentment': 'I\'m resentful at',
    'switch_list_view': 'Switch to List View',
    'switch_table_view': 'Switch to Table View',
    // 8th Step Amends
    'eighth_step_title': '8th Step list',
    'eighth_step_main_tab': 'Main',
    'eighth_step_view_tab': 'View',
    'eighth_step_yes': 'Yes',
    'eighth_step_no': 'No',
    'eighth_step_maybe': 'Maybe',
    'add_person': 'Add Person',
    'edit_person': 'Edit Person',
    'delete_person': 'Delete Person',
    'person_name': 'Name',
    'amends': 'Amends',
    'amends_needed': 'Amends Needed',
    'amends_done': 'Amends Done',
    'amends_done_question': 'Amends Done?',
    'column': 'Column',
    'enter_name': 'Enter name',
    'enter_amends': 'Enter amends needed',
    'confirm_delete_person': 'Delete this person?',
    'person_name_required': 'Name is required',
    'optional': 'Optional',
    // Evening Ritual
    'evening_ritual_title': 'Evening Ritual',
    'evening_ritual_form_tab': 'Today',
    'evening_ritual_list_tab': 'History',
    'reflection_type_resentful': 'I was resentful towards',
    'reflection_type_selfish': 'I was selfish when',
    'reflection_type_dishonest': 'I was dishonest when',
    'reflection_type_afraid': 'I was afraid when',
    'reflection_type_apology_owed': 'I owe an apology to',
    'reflection_type_kept_to_myself': 'I kept to myself (should have shared)',
    'reflection_type_kind_loving': 'I was kind and loving toward',
    'reflection_type_could_do_better': 'I could have done better by',
    'reflection_type_gods_forgiveness': 'God\'s forgiveness (what I ask for)',
    'reflection_type_corrective_measures': 'Corrective measures (what will I do tomorrow)',
    'add_reflection': 'Add Reflection',
    'edit_reflection': 'Edit Reflection',
    'reflection_detail': 'Detail',
    'thinking_focus_question': 'Where was my attention focused today?',
    'thinking_self': 'Thinking of myself',
    'thinking_others': 'Thinking of others',
    'slider_completely_self': 'Completely Self-Focused',
    'slider_mostly_self': 'Mostly Self-Focused',
    'slider_leaning_self': 'Leaning Self-Focused',
    'slider_balanced': 'Balanced',
    'slider_leaning_others': 'Leaning Others-Focused',
    'slider_mostly_others': 'Mostly Others-Focused',
    'slider_completely_others': 'Completely Others-Focused',
    'save_reflection': 'Save',
    'reflection_saved': 'Reflection saved',
    'no_reflections': 'No reflections yet',
    'no_reflections_hint': 'Tap the calendar to add your first evening reflection',
    'reflection_entries_count': '%d entries',
    'delete_reflection': 'Delete Reflection',
    'delete_reflection_confirm': 'Delete this reflection?',
    'reflection_deleted': 'Reflection deleted',
    'select_reflection_type': 'Select reflection type',
    'past_date_read_only': 'This date is in the past and cannot be edited. Only today\'s entry can be modified.',
    'delete_day': 'Delete All Reflections',
    'confirm_delete_day': 'Delete all {count} reflections for {date}?',
    'day_deleted': 'All reflections deleted',
    // Gratitude
    'gratitude_title': 'Gratitude',
    'gratitude_today_tab': 'Today',
    'gratitude_view_tab': 'View',
    'gratitude_today_subtitle': 'What are you grateful for today?',
    'gratitude_add_entry': 'Add Gratitude',
    'gratitude_edit_entry': 'Edit Gratitude',
    'gratitude_towards_label': 'Gratitude towards',
    'gratitude_towards_hint': 'Person, place, or thing',
    'gratitude_for_label': 'Grateful for',
    'gratitude_for_hint': 'What about them are you grateful for?',
    'gratitude_no_entries': 'No gratitude entries yet',
    'gratitude_no_entries_today': 'No gratitude entries for today',
    'gratitude_no_entries_hint': 'Start your gratitude journal in the Today tab',
    'gratitude_entries_count': '%d entries',
    'gratitude_delete_title': 'Delete Gratitude',
    'gratitude_delete_confirm': 'Delete this gratitude entry?',
    'update': 'Update',
    'add': 'Add',
    // Agnosticism
    'agnosticism_title': 'My Current Agnosticism',
    'agnosticism_current_tab': 'Current Paper',
    'agnosticism_archive_tab': 'Archive',
    'agnosticism_side_a_title': 'My Current Agnosticism - The God of My Misunderstanding',
    'agnosticism_side_a_subtitle': 'List the barriers and attributes of your old conception',
    'agnosticism_side_a_empty': 'No barriers listed yet',
    'agnosticism_side_b_title': 'The New Conception - The Power I Need',
    'agnosticism_side_b_subtitle': 'List the attributes of the power you are seeking',
    'agnosticism_side_b_empty': 'No attributes listed yet',
    'agnosticism_add_barrier_hint': 'Add a barrier or attribute...',
    'agnosticism_add_attribute_hint': 'Add an attribute...',
    'agnosticism_turn_page': 'Turn Page',
    'agnosticism_finalize': 'Finalize & Archive',
    'agnosticism_start_new': 'Start New Paper',
    'agnosticism_peek_tooltip': 'Long press to peek at Side A',
    'agnosticism_archive_empty': 'No archived papers yet',
    'agnosticism_archive_empty_hint': 'Complete your first paper to see it here',
    'agnosticism_no_attributes': 'No attributes yet',
    'agnosticism_contemplation': 'Contemplation',
    // Help Content - 4th Step
    'help_4th_step_title': '4th Step Inventory - Purpose & Guidance',
    'help_4th_step_purpose_title': 'Why This Inventory?',
    'help_4th_step_purpose': 'The 4th Step asks us to make "a searching and fearless moral inventory." This tool helps identify resentments - the root of our spiritual illness. By examining what hurt us and our part in it, we prepare for freedom from the bondage of self.',
    'help_4th_step_fields_title': 'Understanding the Fields',
    'help_4th_step_fields': '• "I\'m resentful at" - The person, institution, or principle\n• "The Cause" - What they did or said that hurt\n• "Affects my" - Which part of self was threatened (self-esteem, security, ambitions, relationships, sex)\n• "My take" - Where was I selfish, dishonest, self-seeking, or frightened?\n• "Shortcomings" - Character defects revealed (fear, pride, anger, etc.)',
    'help_4th_step_i_am_title': 'The "I Am" Concept',
    'help_4th_step_i_am': '"I Am" definitions represent core identities tied to resentments (e.g., "I am the son", "I am the employee"). These help track patterns where specific roles trigger recurring character defects. This reveals which identities need spiritual realignment.',
    // Help Content - 8th Step
    'help_8th_step_title': '8th Step Amends List - Purpose & Guidance',
    'help_8th_step_purpose_title': 'Why Make This List?',
    'help_8th_step_purpose': 'Step 8 asks us to make "a list of all persons we had harmed, and became willing to make amends to them all." This prepares us for Step 9. Willingness, not action yet - we\'re building readiness to clean up our side of the street.',
    'help_8th_step_fields_title': 'Understanding the Columns',
    'help_8th_step_fields': '• Name - The person harmed\n• Column (optional) - Reference to 4th Step column (if resentment existed)\n• Amends Needed - What harm did I cause? What do I need to make right?\n• Amends Done - Track when you\'ve completed the 9th Step amend',
    // Help Content - Evening Ritual
    'help_evening_ritual_title': 'Evening Ritual - Purpose & Guidance',
    'help_evening_ritual_purpose_title': 'Why Review Each Day?',
    'help_evening_ritual_purpose': 'The Big Book (p.86) instructs: "Review the day. Were we resentful, selfish, dishonest or afraid?" This daily practice keeps us spiritually fit, catching defects quickly before they compound. Regular inventory prevents the build-up that leads to relapse.',
    'help_evening_ritual_reflection_types_title': 'The Ten Categories',
    'help_evening_ritual_reflection_types': 'Track daily where you:\n• Were resentful, selfish, dishonest, or afraid\n• Owe apologies or kept secrets\n• Showed kindness or could improve\n• Seek God\'s forgiveness\n• Plan corrective actions for tomorrow\n\nThese categories align with Big Book guidance for daily review.',
    'help_evening_ritual_focus_title': 'Self vs. Others Focus',
    'help_evening_ritual_focus': 'The slider tracks: "Where was my attention today?" Recovery shifts us from self-centeredness to being useful to others. Daily tracking reveals patterns - am I growing in selflessness or slipping into self-absorption?',
    // Help Content - Gratitude
    'help_gratitude_title': 'Gratitude Journal - Purpose & Guidance',
    'help_gratitude_purpose_title': 'Why Practice Gratitude?',
    'help_gratitude_purpose': 'Gratitude is the antidote to resentment and self-pity. The Big Book states we cannot be helpful when harboring resentment. Daily gratitude rewires our minds toward abundance rather than lack, shifting focus from what\'s wrong to what\'s right. This builds spiritual fitness.',
    'help_gratitude_practice_title': 'The Daily Practice',
    'help_gratitude_practice': 'Each day, record what you\'re grateful for using two fields: "Gratitude towards" (person, place, or thing) and "Grateful for" (what specifically about them). For example: towards "My sponsor" grateful for "Their patience and wisdom during my struggle." This structure helps you be specific and see patterns of grace in your life.',
    // Help Content - Agnosticism
    'help_agnosticism_title': 'My Current Agnosticism - Purpose & Guidance',
    'help_agnosticism_purpose_title': 'Why Examine My Conception of God?',
    'help_agnosticism_purpose': 'Step 2 requires us to believe in "a Power greater than ourselves." Many come with distorted God-concepts that block connection. This exercise, from the "We Agnostics" chapter, helps discard what doesn\'t work and build a new, personal understanding of a Higher Power.',
    'help_agnosticism_side_a_title': 'Side A - The God of My Misunderstanding',
    'help_agnosticism_side_a': 'List the barriers and negative attributes of your old God-concept: judgmental, punishing, distant, demanding perfection, etc. These are the ideas that made connection impossible. Acknowledge them to release them.',
    'help_agnosticism_side_b_title': 'Side B - The Power I Need',
    'help_agnosticism_side_b': 'List attributes of the Power you seek: loving, patient, forgiving, present, accepting, empowering, etc. This becomes your new conception - one that makes sense to you and enables real relationship. Design your own Higher Power.',
    'help_agnosticism_process_title': 'The Process',
    'help_agnosticism_process': 'Work on Side A first. When complete, "turn the page" to Side B. You can peek back at Side A while working. When both sides feel complete, finalize to archive. Over time, you may create multiple papers as your understanding deepens. Each paper is a snapshot of your spiritual evolution.',
  },
  'da': {
    'app_title': '4. Trins Inventory',
    'form_title': 'Form',
    'entries_title': 'Indtastninger',
    'settings_title': 'Indstillinger',
    'data_management': 'Data Håndtering',
    'export_json': 'Eksporter til JSON',
    'import_json': 'Importer fra JSON',
    'clear_all': 'Slet Alle Indtastninger',
    'cancel': 'Annuller',
    'confirm_clear': 'Dette vil permanent slette alle indtastninger. Fortsæt?',
    'delete_entry': 'Slet Indtastning',
    'delete_confirm': 'Er du sikker på, at du vil slette denne indtastning?',
    'delete': 'Slet',
    'edit_entry': 'Rediger Indtastning',
    'entry_deleted': 'Indtastning slettet',
    'my_take': 'Min(e) handling(er)',
    'shortcomings': 'Karakterdefekt(er)',
    'affect_my': 'Påvirker min',
    'i_am': 'Jeg er',
    'i_am_definitions': 'Jeg er definitioner',
    'add_i_am': 'Tilføj Jeg er',
    'edit_i_am': 'Rediger Jeg er',
    'delete_i_am': 'Slet Jeg er',
    'i_am_name': 'Jeg er navn',
    'reason': 'Årsag',
    'reason_to_exist_optional': 'Eksistensgrundlag',
    'select_i_am': 'Vælg Jeg er',
    'no_i_am_selected': 'Standard (ingen Jeg er)',
    'confirm_delete_i_am': 'Slet denne Jeg er definition?',
    'i_am_name_required': 'Jeg er navn er påkrævet',
    'search': 'Søg',
    'save_changes': 'Gem Ændringer',
    'add_entry': 'Tilføj Indtastning',
    'cancel_edit': 'Annuller Redigering',
    'googlefetch': 'Hent data fra Google Drive og overskriv lokale data',
    'sync_google_drive': 'Synkroniser med Google Drive',
    'drive_upload_success': 'Drive upload succes (%s indtastninger)',
    'no_entries': 'Ingen indtastninger',
    'confirm_google_fetch': 'Hent data fra Google Drive og overskriv lokale data?',
    'fetch': 'Hent',
    'fetching_data': 'Henter data fra Google Drive...',
    'select_restore_point': 'Vælg Gendannelsespunkt',
    'restore_point_latest': 'Seneste (Nuværende)',
    'restore_from_backup': 'Gendan fra Backup',
    'loading_backups': 'Indlæser backups...',
    'no_backups_available': 'Ingen backups tilgængelige',
    'part_tooltip': 'Har jeg været selvisk, uærlig, egoistisk eller skræmt?',
    'close': 'Luk',
    'resentment': 'Jeg er vred på',
    'switch_list_view': 'Skift til Listevisning',
    'switch_table_view': 'Skift til Tabelvisning',
    // 8th Step Amends
    'eighth_step_title': '8. Trins liste',
    'eighth_step_main_tab': 'Liste',
    'eighth_step_view_tab': 'Vis',
    'eighth_step_yes': 'Ja',
    'eighth_step_no': 'Nej',
    'eighth_step_maybe': 'Måske',
    'add_person': 'Tilføj Person',
    'edit_person': 'Rediger Person',
    'delete_person': 'Slet Person',
    'person_name': 'Navn',
    'amends': 'Erstatning',
    'amends_needed': '9. trin',
    'amends_done': '9. trin fuldført',
    'amends_done_question': '9. trin fuldført?',
    'column': 'Kolonne',
    'enter_name': 'Indtast navn',
    'enter_amends': '9. trin',
    'confirm_delete_person': 'Slet denne person?',
    'person_name_required': 'Navn er påkrævet',
    'optional': 'Valgfrit',
    // Evening Ritual (Danish)
    'evening_ritual_title': 'Aftenritual',
    'evening_ritual_form_tab': 'I dag',
    'evening_ritual_list_tab': 'Historik',
    'reflection_type_resentful': 'Jeg var vred på',
    'reflection_type_selfish': 'Jeg var selvisk da',
    'reflection_type_dishonest': 'Jeg var uærlig da',
    'reflection_type_afraid': 'Jeg var bange da',
    'reflection_type_apology_owed': 'Jeg skylder en undskyldning til',
    'reflection_type_kept_to_myself': 'Jeg holdt for mig selv (burde have delt)',
    'reflection_type_kind_loving': 'Jeg var venlig og kærlig overfor',
    'reflection_type_could_do_better': 'Jeg kunne have gjort det bedre ved',
    'reflection_type_gods_forgiveness': 'Guds tilgivelse (hvad jeg beder om)',
    'reflection_type_corrective_measures': 'Korrigerende handlinger (hvad vil jeg gøre i morgen)',
    'add_reflection': 'Tilføj Refleksion',
    'edit_reflection': 'Rediger Refleksion',
    'reflection_detail': 'Detalje',
    'thinking_focus_question': 'Hvor var min opmærksomhed fokuseret i dag?',
    'thinking_self': 'Tænker på mig selv',
    'thinking_others': 'Tænker på andre',
    'slider_completely_self': 'Fuldstændig Selvfokuseret',
    'slider_mostly_self': 'Mest Selvfokuseret',
    'slider_leaning_self': 'Hælder til Selvfokuseret',
    'slider_balanced': 'Afbalanceret',
    'slider_leaning_others': 'Hælder til Andrefokuseret',
    'slider_mostly_others': 'Mest Andrefokuseret',
    'slider_completely_others': 'Fuldstændig Andrefokuseret',
    'save_reflection': 'Gem',
    'reflection_saved': 'Refleksion gemt',
    'no_reflections': 'Ingen refleksioner endnu',
    'no_reflections_hint': 'Tryk på kalenderen for at tilføje din første aftenrefleksion',
    'reflection_entries_count': '%d indtastninger',
    'delete_reflection': 'Slet Refleksion',
    'delete_reflection_confirm': 'Slet denne refleksion?',
    'reflection_deleted': 'Refleksion slettet',
    'select_reflection_type': 'Vælg refleksionstype',
    'past_date_read_only': 'Denne dato er i fortiden og kan ikke redigeres. Kun dagens indtastning kan ændres.',
    'delete_day': 'Slet Alle Refleksioner',
    'confirm_delete_day': 'Slet alle {count} refleksioner for {date}?',
    'day_deleted': 'Alle refleksioner slettet',
    // Gratitude (Danish)
    'gratitude_title': 'Taknemmelighed',
    'gratitude_today_tab': 'I dag',
    'gratitude_view_tab': 'Vis',
    'gratitude_today_subtitle': 'Hvad er du taknemmelig for i dag?',
    'gratitude_add_entry': 'Tilføj Taknemmelighed',
    'gratitude_edit_entry': 'Rediger Taknemmelighed',
    'gratitude_towards_label': 'Taknemmelighed over for',
    'gratitude_towards_hint': 'Person, sted eller ting',
    'gratitude_for_label': 'Taknemmelig for',
    'gratitude_for_hint': 'Hvad ved dem er du taknemmelig for?',
    'gratitude_no_entries': 'Ingen taknemmeligheds-indlæg endnu',
    'gratitude_no_entries_today': 'Ingen taknemmeligheds indtastninger for i dag',
    'gratitude_no_entries_hint': 'Start din taknemmeligheds dagbog i I dag fanen',
    'gratitude_entries_count': '%d indtastninger',
    'gratitude_delete_title': 'Slet Taknemmelighed',
    'gratitude_delete_confirm': 'Slet denne taknemmeligheds indtastning?',
    'update': 'Opdater',
    'add': 'Tilføj',
    // Agnosticism (Danish)
    'agnosticism_title': 'Min Nuværende Agnosticisme',
    'agnosticism_current_tab': 'Nuværende Papir',
    'agnosticism_archive_tab': 'Arkiv',
    'agnosticism_side_a_title': 'Min Nuværende Agnosticisme - Den Gud Jeg Misforstår',
    'agnosticism_side_a_subtitle': 'Oplist barriererne og egenskaberne ved din gamle opfattelse',
    'agnosticism_side_a_empty': 'Ingen barrierer listet endnu',
    'agnosticism_side_b_title': 'Den Nye Opfattelse - Den Kraft Jeg Har Brug For',
    'agnosticism_side_b_subtitle': 'Oplist egenskaberne ved den kraft du søger',
    'agnosticism_side_b_empty': 'Ingen egenskaber listet endnu',
    'agnosticism_add_barrier_hint': 'Tilføj en barriere eller egenskab...',
    'agnosticism_add_attribute_hint': 'Tilføj en egenskab...',
    'agnosticism_turn_page': 'Vend Side',
    'agnosticism_finalize': 'Færdiggør & Arkivér',
    'agnosticism_start_new': 'Start Nyt Papir',
    'agnosticism_peek_tooltip': 'Tryk længe for at kigge på Side A',
    'agnosticism_archive_empty': 'Ingen arkiverede papirer endnu',
    'agnosticism_archive_empty_hint': 'Færdiggør dit første papir for at se det her',
    'agnosticism_no_attributes': 'Ingen egenskaber endnu',
    'agnosticism_contemplation': 'Kontemplation',
    // Help Content - 4th Step (Danish)
    'help_4th_step_title': '4. Trins Inventory - Formål & Vejledning',
    'help_4th_step_purpose_title': 'Hvorfor Dette Inventory?',
    'help_4th_step_purpose': '4. Trin beder os om at lave "en grundig og frygtløs moralsk inventarliste." Dette værktøj hjælper med at identificere vrede - roden til vores åndelige sygdom. Ved at undersøge hvad der sårede os og vores rolle i det, forbereder vi os til frihed fra selvets fangenskab.',
    'help_4th_step_fields_title': 'Forståelse af Felterne',
    'help_4th_step_fields': '• "Jeg er vred på" - Personen, institutionen eller princippet\n• "Årsagen" - Hvad de gjorde eller sagde der sårede\n• "Påvirker min" - Hvilken del af selvet blev truet (selvværd, sikkerhed, ambitioner, relationer, sex)\n• "Min(e) handling(er)" - Hvor var jeg selvisk, uærlig, egoistisk eller skræmt?\n• "Karakterdefekt(er)" - Afslørede karakterfejl (frygt, stolthed, vrede osv.)',
    'help_4th_step_i_am_title': '"Jeg Er" Konceptet',
    'help_4th_step_i_am': '"Jeg er" definitioner repræsenterer kerneidentiteter knyttet til vrede (f.eks. "Jeg er sønnen", "Jeg er medarbejderen"). Disse hjælper med at spore mønstre, hvor specifikke roller udløser tilbagevendende karakterfejl. Dette afslører hvilke identiteter der har brug for åndelig tilpasning.',
    // Help Content - 8th Step (Danish)
    'help_8th_step_title': '8. Trins Erstatningsliste - Formål & Vejledning',
    'help_8th_step_purpose_title': 'Hvorfor Lave Denne Liste?',
    'help_8th_step_purpose': 'Trin 8 beder os om at lave "en liste over alle personer vi har skadet, og blive villige til at erstatte dem alle." Dette forbereder os til trin 9. Vilje, ikke handling endnu - vi bygger parathed til at rydde op på vores side af gaden.',
    'help_8th_step_fields_title': 'Forståelse af Kolonnerne',
    'help_8th_step_fields': '• Navn - Den skadede person\n• Kolonne (valgfrit) - Reference til 4. trins kolonne (hvis vrede eksisterede)\n• Erstatning nødvendig - Hvilken skade forvoldte jeg? Hvad skal jeg gøre godt igen?\n• Erstatning udført - Spor når du har fuldført 9. trins erstatning',
    // Help Content - Evening Ritual (Danish)
    'help_evening_ritual_title': 'Aftenritual - Formål & Vejledning',
    'help_evening_ritual_purpose_title': 'Hvorfor Gennemgå Hver Dag?',
    'help_evening_ritual_purpose': 'Den Store Bog (s.86) instruerer: "Gennemgå dagen. Var vi vrede, selviske, uærlige eller bange?" Denne daglige praksis holder os åndeligt fit, fanger fejl hurtigt før de forværres. Regelmæssig inventar forhindrer opbygning der fører til tilbagefald.',
    'help_evening_ritual_reflection_types_title': 'De Ti Kategorier',
    'help_evening_ritual_reflection_types': 'Spor dagligt hvor du:\n• Var vred, selvisk, uærlig eller bange\n• Skylder undskyldninger eller holdt hemmeligheder\n• Viste venlighed eller kunne forbedre\n• Søger Guds tilgivelse\n• Planlæg korrigerende handlinger for i morgen\n\nDisse kategorier stemmer overens med Den Store Bogs vejledning for daglig gennemgang.',
    'help_evening_ritual_focus_title': 'Selv vs. Andre Fokus',
    'help_evening_ritual_focus': 'Skyderen sporer: "Hvor var min opmærksomhed i dag?" Bedring flytter os fra selvcentrering til at være nyttige for andre. Daglig sporing afslører mønstre - vokser jeg i uselviskhed eller glider jeg ind i selvoptagethed?',
    // Help Content - Gratitude (Danish)
    'help_gratitude_title': 'Taknemmeligheds Dagbog - Formål & Vejledning',
    'help_gratitude_purpose_title': 'Hvorfor Øve Taknemmelighed?',
    'help_gratitude_purpose': 'Taknemmelighed er modgiften mod vrede og selvmedlidenhed. Den Store Bog siger vi ikke kan være hjælpsomme når vi nærer vrede. Daglig taknemmelighed omkobler vores sind mod overflod frem for mangel, flytter fokus fra hvad der er galt til hvad der er rigtigt. Dette bygger åndelig fitness.',
    'help_gratitude_practice_title': 'Den Daglige Praksis',
    'help_gratitude_practice': 'Hver dag, noter hvad du er taknemmelig for ved hjælp af to felter: "Taknemmelighed over for" (person, sted eller ting) og "Taknemmelig for" (hvad specifikt ved dem). For eksempel: over for "Min sponsor" taknemmelig for "Deres tålmodighed og visdom under min kamp." Denne struktur hjælper dig med at være specifik og se mønstre af nåde i dit liv.',
    // Help Content - Agnosticism (Danish)
    'help_agnosticism_title': 'Min Nuværende Agnosticisme - Formål & Vejledning',
    'help_agnosticism_purpose_title': 'Hvorfor Undersøge Min Gudsopfattelse?',
    'help_agnosticism_purpose': 'Trin 2 kræver at vi tror på "en Kraft større end os selv." Mange kommer med forvrængede Guds-koncepter der blokerer forbindelse. Denne øvelse, fra kapitlet "Vi Agnostikere", hjælper med at kassere hvad der ikke virker og opbygge en ny, personlig forståelse af en Højere Magt.',
    'help_agnosticism_side_a_title': 'Side A - Den Gud Jeg Misforstår',
    'help_agnosticism_side_a': 'List barriererne og negative egenskaber ved din gamle Guds-opfattelse: dømmende, straffende, fjern, kræver perfektion osv. Dette er ideerne der gjorde forbindelse umulig. Anerkend dem for at frigive dem.',
    'help_agnosticism_side_b_title': 'Side B - Den Kraft Jeg Har Brug For',
    'help_agnosticism_side_b': 'List egenskaber ved den Kraft du søger: kærlig, tålmodig, tilgivende, til stede, accepterende, styrkende osv. Dette bliver din nye opfattelse - en der giver mening for dig og muliggør ægte forhold. Design din egen Højere Magt.',
    'help_agnosticism_process_title': 'Processen',
    'help_agnosticism_process': 'Arbejd først på Side A. Når færdig, "vend siden" til Side B. Du kan kigge tilbage på Side A mens du arbejder. Når begge sider føles færdige, færdiggør til arkiv. Over tid kan du oprette flere papirer efterhånden som din forståelse uddybes. Hvert papir er et øjebliksbillede af din åndelige udvikling.',
  },
};

String t(BuildContext context, String key) {
  final locale = Localizations.localeOf(context);
  return localizedValues[locale.languageCode]?[key] ??
      localizedValues['en']?[key] ??
      key; // fallback to key itself
}
