import 'package:flutter/material.dart';

final Map<String, Map<String, String>> localizedValues = {
  'en': {
    'app_title': '4th Step Inventory',
    'form_title': 'Form',
    'entries_title': 'Entries',
    'settings_title': 'Settings',
    'data_management': 'Data Management',
    'export_csv': 'Export to CSV',
    'import_csv': 'Import from CSV',
    'export_json': 'Export to JSON',
    'import_json': 'Import from JSON',
    'clear_all': 'Clear All Entries',
    'cancel': 'Cancel',
    'confirm_clear': 'This will delete all entries permanently. Continue?',
    'delete_entry': 'Delete Entry',
    'delete_confirm': 'Are you sure you want to delete this entry?',
    'resentment': 'I\'m resentful at',
    'reason': 'The Cause',
    'affect': 'Affects my',
    'part': 'My take',
    'defect': 'Shortcommings',
    'my_take': 'My take',
    'shortcomings': 'Shortcommings',
    'affect_my': 'Affects my',
    'i_am': 'I Am',
    'i_am_definitions': 'I Am Definitions',
    'add_i_am': 'Add I Am',
    'edit_i_am': 'Edit I Am',
    'delete_i_am': 'Delete I Am',
    'i_am_name': 'I Am name',
    'reason_to_exist': 'Reason to exist',
    'reason_to_exist_optional': 'Reason to exist (optional)',
    'select_i_am': 'Select I Am',
    'no_i_am_selected': 'Standard (no I Am)',
    'confirm_delete_i_am': 'Delete this I Am definition?',
    'i_am_name_required': 'I Am name is required',
    'default_i_am': 'Sober member of AA',
    'search': 'Search',
    'save_changes': 'Save Changes',
    'add_entry': 'Add Entry',
    'cancel_edit': 'Cancel Edit',
    'fill_required_fields': 'Please fill in required fields',
    'entry_updated': 'Entry updated successfully',
    'entry_added': 'Entry added successfully',
    'googlefetch': 'Fetch data from Google Drive and overwrite local data',
    'sync_google_drive': 'Sync with Google Drive',
    'drive_upload_success': 'Drive upload successful (%s entries)',
    'no_entries': 'No entries',
    'confirm_google_fetch': 'Fetch data from Google Drive and overwrite local data?',
    'fetch': 'Fetch',
    'part_tooltip': 'Have I been Selfish, dishonest, self-seeking or frightened?',
    'close': 'Close',
  },
  'da': {
    'app_title': '4. Trins Inventory',
    'form_title': 'Form',
    'entries_title': 'Indtastninger',
    'settings_title': 'Indstillinger',
    'data_management': 'Data Håndtering',
    'export_csv': 'Eksporter til CSV',
    'import_csv': 'Importer fra CSV',
    'export_json': 'Eksporter til JSON',
    'import_json': 'Importer fra JSON',
    'clear_all': 'Slet Alle Indtastninger',
    'cancel': 'Annuller',
    'confirm_clear': 'Dette vil permanent slette alle indtastninger. Fortsæt?',
    'delete_entry': 'Slet Indtastning',
    'delete_confirm': 'Er du sikker på, at du vil slette denne indtastning?',
    'resentment': 'Jeg er vred på',
    'reason': 'Årsag',
    'affect': 'Påvirker mine',
    'part': 'Min rolle',
    'defect': 'Karakterdefekt(er)',
    'my_take': 'Min opfattelse',
    'shortcomings': 'Mangler',
    'affect_my': 'Påvirker min',
    'i_am': 'Jeg er',
    'i_am_definitions': 'Jeg er definitioner',
    'add_i_am': 'Tilføj Jeg er',
    'edit_i_am': 'Rediger Jeg er',
    'delete_i_am': 'Slet Jeg er',
    'i_am_name': 'Jeg er navn',
    'reason_to_exist': 'Grund til at eksistere',
    'reason_to_exist_optional': 'Grund til at eksistere (valgfri)',
    'select_i_am': 'Vælg Jeg er',
    'no_i_am_selected': 'Standard (ingen Jeg er)',
    'confirm_delete_i_am': 'Slet denne Jeg er definition?',
    'i_am_name_required': 'Jeg er navn er påkrævet',
    'default_i_am': 'Ædru medlem af AA',
    'search': 'Søg',
    'save_changes': 'Gem Ændringer',
    'add_entry': 'Tilføj Indtastning',
    'cancel_edit': 'Annuller Redigering',
    'fill_required_fields': 'Udfyld venligst alle påkrævede felter',
    'entry_updated': 'Indtastning opdateret',
    'entry_added': 'Indtastning tilføjet',
    'googlefetch': 'Hent data fra Google Drive og overskriv lokale data',
    'sync_google_drive': 'Synkroniser med Google Drive',
    'drive_upload_success': 'Drive upload succes (%s indtastninger)',
    'no_entries': 'Ingen indtastninger',
    'confirm_google_fetch': 'Hent data fra Google Drive og overskriv lokale data?',
    'fetch': 'Hent',
    'part_tooltip': 'Har jeg været selvisk, uærlig, egoistisk eller skræmt?',
    'close': 'Luk',
  },
};

String t(BuildContext context, String key) {
  final locale = Localizations.localeOf(context);
  return localizedValues[locale.languageCode]?[key] ??
      localizedValues['en']?[key] ??
      key; // fallback to key itself
}
