import 'package:flutter/material.dart';

final Map<String, Map<String, String>> localizedValues = {
  'en': {
    'app_title': 'AA 4 Step Inventory',
    'form_title': 'Form',
    'entries_title': 'Entries',
    'settings_title': 'Settings',
    'data_management': 'Data Management',
    'export_csv': 'Export to CSV',
    'import_csv': 'Import from CSV',
    'clear_all': 'Clear All Entries',
    'cancel': 'Cancel',
    'confirm_clear': 'This will delete all entries permanently. Continue?',
    'delete_entry': 'Delete Entry',
    'delete_confirm': 'Are you sure you want to delete this entry?',
    'resentment': 'I\'m resentful at',
    'reason': 'The Cause',
    'affect': 'Affects my',
    'part': 'My take',
    'defect': 'Shortcommings',
    'save_changes': 'Save Changes',
    'add_entry': 'Add Entry',
    'cancel_edit': 'Cancel Edit',
    'fill_required_fields': 'Please fill in required fields',
    'entry_updated': 'Entry updated successfully',
    'entry_added': 'Entry added successfully',
    'googlefetch': 'Fetch data from Google Drive and overwrite local data',
    'sync_google_drive': 'Sync with Google Drive',
    'drive_upload_success': 'Drive upload successful (%s entries)',
    'no_entries': 'No entries',
    'confirm_google_fetch': 'Fetch data from Google Drive and overwrite local data?',
    'fetch': 'Fetch',
    'part_tooltip': 'Have I been Selfish, dishonest, self-seeking or frightened?',
    'close': 'Close',
  },
  'da': {
    'app_title': 'AA 4 Trins Inventory',
    'form_title': 'Form',
    'entries_title': 'Indtastninger',
    'settings_title': 'Indstillinger',
    'data_management': 'Data Håndtering',
    'export_csv': 'Eksporter til CSV',
    'import_csv': 'Importer fra CSV',
    'clear_all': 'Slet Alle Indtastninger',
    'cancel': 'Annuller',
    'confirm_clear': 'Dette vil permanent slette alle indtastninger. Fortsæt?',
    'delete_entry': 'Slet Indtastning',
    'delete_confirm': 'Er du sikker på, at du vil slette denne indtastning?',
    'resentment': 'Jeg er vred på',
    'reason': 'Årsag',
    'affect': 'Påvirker mine',
    'part': 'Min rolle',
    'defect': 'Karakterdefekt(er)',
    'save_changes': 'Gem Ændringer',
    'add_entry': 'Tilføj Indtastning',
    'cancel_edit': 'Annuller Redigering',
    'fill_required_fields': 'Udfyld venligst alle påkrævede felter',
    'entry_updated': 'Indtastning opdateret',
    'entry_added': 'Indtastning tilføjet',
    'googlefetch': 'Hent data fra Google Drive og overskriv lokale data',
    'sync_google_drive': 'Synkroniser med Google Drive',
    'drive_upload_success': 'Drive upload succes (%s indtastninger)',
    'no_entries': 'Ingen indtastninger',
    'confirm_google_fetch': 'Hent data fra Google Drive og overskriv lokale data?',
    'fetch': 'Hent',
    'part_tooltip': 'Har jeg været selvisk, uærlig, egoistisk eller skræmt?',
    'close': 'Luk',
  },
};

String t(BuildContext context, String key) {
  final locale = Localizations.localeOf(context);
  return localizedValues[locale.languageCode]?[key] ??
      localizedValues['en']?[key] ??
      key; // fallback to key itself
}
